# -*- coding: utf-8 -*-
"""iris_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryyEmtSySF1frc_UQKLwyPVUW8AWuHY0
"""

from sklearn.datasets import load_iris

iris = load_iris()

x = iris.data
y = iris.target

#data Exploration
print(x.shape)
print(y.shape)

import pandas as pd
df = pd.DataFrame(x,columns = iris.feature_names)
df['target'] = y
print(df.head())
print(df.tail())
print(df.describe())

df.plot()

df.plot.scatter(x='petal length (cm)', y='petal width (cm)', c='target', colormap='viridis')

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

y_test

y_train

x_train.shape

from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(100,2),activation='tanh',solver='adam',random_state=42,max_iter=500)

model.fit(x_train,y_train)

#test
y_pred = model.predict(x_test)

y_test

from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))

